### ISSUE TITLE
Storing key in secure storage

### ISSUE THREAD

**Issue by hybridNeo** [jforissier/secvideo_demo#1]
In this application you have put the key in the TA code itself, I am building a real world app, I wanted to know how to put the key in secure storage and access it. Because secure storage can be accessed only in runtime.

**Comment by jforissier** [comment]
One option is to store the key into secure storage at the time of manufacture, as software is loaded onto the device. For instance, implement a "set key" command in the TA, which would simply write the key using `TEE_CreatePersistentObject()`. Invoke it once using a special client application when the device is still in a controlled environment. This technique is not very flexible, though (what if one needs to re-install the software in the device?).

Another option is to pass the key at runtime, encrypted with a device-specific key that is known to OP-TEE, i.e., a key derived from the one-time-programmable, master hardware unique key (`tee_otp_get_hw_unique_key()`). Real-world DRM applications would typically contain complex key derivation mechanisms but please check the OP-TEE specific extensions to `TEE_DeriveKey()`: Concat KDF, HKDF, PBKDF2. They may come in handy.

**Comment by hybridNeo** [comment]
Thank you for the reply, I shall look into it.
Also with regard to your hikey aosp repository, are those versions of OPTEE
test and client the only supported ones with aosp or can I update them to
respective masters.

**Comment by jforissier** [comment]
You should be able to use the latest masters of optee_test and optee_client with AOSP, but please note that the latest optee_client and optee_os do not need optee_linuxdriver anymore and they are not compatible with it. So depending on your kernel, you may have to backport the "generic driver" patches -- see https://github.com/linaro-swg/linux/commits/optee_v9.
