### ISSUE TITLE
secvideo_demo based source's tee_svc_framebuffer_update's memcpy gives TEE-CORE: Panic

### ISSUE THREAD

**Issue by ajithpv** [jforissier/secvideo_demo#4]
I'm doing a display image dump and the reference I have taken is secvideo_demo.
I have changed the source to work with new OP-TEE and clear screen is working for me. The 'tee_svc_framebuffer_update' function name changed to 'syscall_framebuffer_update' but the logic is same for doing the image dump (i.e I'm also using the memcpy).
Even though I'm calling the same 'syscall_framebuffer_update' for clearing as well as image dumping, I'm getting the below error when I'm trying to use image dump.

```
ERROR:   TEE-CORE: 
ERROR:   TEE-CORE: Core data-abort at address 0x0 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000005  ttbr0 0x8c15e06a  ttbr1 0x8c15806a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x20000033
ERROR:   TEE-CORE:  r0 0x8c132d2e      r4 0x0003fc00    r8 0x00200000   r12 0x8c132d11
ERROR:   TEE-CORE:  r1 0x0000004c      r5 0x0003fc00    r9 0x8b600000    sp 0x8c160e58
ERROR:   TEE-CORE:  r2 0x00000003      r6 0x00000000   r10 0x00000000    lr 0x8c10b355
ERROR:   TEE-CORE:  r3 0x8c132d12      r7 0x00000000   r11 0x00000615    pc 0x8c10b362
ERROR:   TEE-CORE: Panic
```

But, the clear screen is working fine and the only difference I have seen is that, clear screen passing the data as 16KB with a do-while where as the image dump passing the whole image at once.

Please let me know what this error means and how I can resolve this.

**Comment by jforissier** [comment]
Hi @ajithpv,

The error mean you are de-referencing a NULL pointer inside the OP-TEE core, at address `0x8c10b362`. Try `addr2line -f -p -e out/*/core/tee.elf 8c10b362` and you should obtain the function name and file/line number information (side note: I'm surprised the error doesn't show a full call stack, is your optee_os recent enough?).

**Comment by ajithpv** [comment]
Thank you so much @jforissier for the _addr2line_ command. I found the problem and now the Panic got resolved.
I'm using `OP-TEE version: 2.4.0-130-gf9a64f12-dev` for my purpose.

**Comment by jforissier** [comment]
> I'm using `OP-TEE version: 2.4.0-130-gf9a64f12-dev` for my purpose.

OK, then you might want to upgrade or just cherry-pick commit e4c86a0756bd ("core: fix print_kernel_stack()"). This should get you a full call stack that you can further interpret with `scripts/symbolize.py`. Not a big deal but it comes handy sometimes.

**Comment by ajithpv** [comment]
Thank you @jforissier , we will do the upgrade once, my colleagues work over on this version.
