### ISSUE TITLE
Displaying on TEE

### ISSUE THREAD

**Issue by tesmnorth** [jforissier/secvideo_demo#5]
Hello mr. forissier,

I have a question about your demo. We can say that your demo has a part of code (display driver etc) for TUI implementation?
My master thesis is about TUI. I research how can I share framebuffer to Normal world. I dont understand structure. Can you show a why for solving this problem?

**Comment by jforissier** [comment]
Hi @tesmnorth,

This code is obsolete now. It is not a display driver ; I used the frame buffer for convenience of the demo. The purpose of this prototype was to investigate ways to implement a "secure video path", that is, sharing memory between normal and secure worlds and preventing normal world from accessing this memory when it contains protected data.
TUI is a complex thing. You definitely need to have a proper display driver in secure world, but also take care of how the display is shared with normal world.

**Comment by tesmnorth** [comment]
- I think, there is no display driver in optee for Hikey platform. I need to write a new display driver for OP-TEE. 
- Do you suggest any advice or idea for display sharing with normal world?
