### ISSUE TITLE
Stopping in "Cloning into '/home/wxlqaz/secvideo_demo/linux'..." 

### ISSUE THREAD

**Issue by wxlqaz** [jforissier/secvideo_demo#6]
Hi,
I am a researcher about TEE. I am following the steps in https://github.com/jforissier/secvideo_demo to install this project in an ubuntu 17.10 computer with enough storage (about 500Gb). However, It was stopped in "Cloning into '/home/wxlqaz/secvideo_demo/linux'..." after typing "git submodule update --init" in step 2. The folder "linux" is existed in "secvideo_demo" directory and it is empty. So could you have some advice about this problem?
Thank you very much.

**Comment by jforissier** [comment]
Hi @wxlqaz ,

I suspect git encountered a network error. You may want to try "git submodule update" again.

However please not this project is quite old! If you are interested in secure data path stuff, you should probably look at the OP-TEE OS option `CFG_SECURE_DATA_PATH=y`. It can be used on the QEMU platform, see https://github.com/OP-TEE/build#7-get-and-build-the-solution.
To use SDP on QEMU, you would build with `make -j9 CFG_SECURE_DATA_PATH=y run`, then run `xtest 1014` in the Normal World console. SDP uses the ION "unmapped heap" feature to manipulate areas of secure memory in normal world.

**Comment by wxlqaz** [comment]
OK, I will try it. Thank you!
